// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package productpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Product) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type CreateProductReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductReq) Reset()         { *m = CreateProductReq{} }
func (m *CreateProductReq) String() string { return proto.CompactTextString(m) }
func (*CreateProductReq) ProtoMessage()    {}
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{1}
}

func (m *CreateProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductReq.Unmarshal(m, b)
}
func (m *CreateProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductReq.Marshal(b, m, deterministic)
}
func (m *CreateProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductReq.Merge(m, src)
}
func (m *CreateProductReq) XXX_Size() int {
	return xxx_messageInfo_CreateProductReq.Size(m)
}
func (m *CreateProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductReq proto.InternalMessageInfo

func (m *CreateProductReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductRes struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRes) Reset()         { *m = CreateProductRes{} }
func (m *CreateProductRes) String() string { return proto.CompactTextString(m) }
func (*CreateProductRes) ProtoMessage()    {}
func (*CreateProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{2}
}

func (m *CreateProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRes.Unmarshal(m, b)
}
func (m *CreateProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRes.Marshal(b, m, deterministic)
}
func (m *CreateProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRes.Merge(m, src)
}
func (m *CreateProductRes) XXX_Size() int {
	return xxx_messageInfo_CreateProductRes.Size(m)
}
func (m *CreateProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRes proto.InternalMessageInfo

func (m *CreateProductRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReq) Reset()         { *m = GetProductReq{} }
func (m *GetProductReq) String() string { return proto.CompactTextString(m) }
func (*GetProductReq) ProtoMessage()    {}
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{3}
}

func (m *GetProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReq.Unmarshal(m, b)
}
func (m *GetProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReq.Marshal(b, m, deterministic)
}
func (m *GetProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReq.Merge(m, src)
}
func (m *GetProductReq) XXX_Size() int {
	return xxx_messageInfo_GetProductReq.Size(m)
}
func (m *GetProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReq proto.InternalMessageInfo

func (m *GetProductReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductRes struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRes) Reset()         { *m = GetProductRes{} }
func (m *GetProductRes) String() string { return proto.CompactTextString(m) }
func (*GetProductRes) ProtoMessage()    {}
func (*GetProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{4}
}

func (m *GetProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRes.Unmarshal(m, b)
}
func (m *GetProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRes.Marshal(b, m, deterministic)
}
func (m *GetProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRes.Merge(m, src)
}
func (m *GetProductRes) XXX_Size() int {
	return xxx_messageInfo_GetProductRes.Size(m)
}
func (m *GetProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRes proto.InternalMessageInfo

func (m *GetProductRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductReq) Reset()         { *m = UpdateProductReq{} }
func (m *UpdateProductReq) String() string { return proto.CompactTextString(m) }
func (*UpdateProductReq) ProtoMessage()    {}
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{5}
}

func (m *UpdateProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductReq.Unmarshal(m, b)
}
func (m *UpdateProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductReq.Marshal(b, m, deterministic)
}
func (m *UpdateProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductReq.Merge(m, src)
}
func (m *UpdateProductReq) XXX_Size() int {
	return xxx_messageInfo_UpdateProductReq.Size(m)
}
func (m *UpdateProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductReq proto.InternalMessageInfo

func (m *UpdateProductReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRes struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRes) Reset()         { *m = UpdateProductRes{} }
func (m *UpdateProductRes) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRes) ProtoMessage()    {}
func (*UpdateProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{6}
}

func (m *UpdateProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRes.Unmarshal(m, b)
}
func (m *UpdateProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRes.Marshal(b, m, deterministic)
}
func (m *UpdateProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRes.Merge(m, src)
}
func (m *UpdateProductRes) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRes.Size(m)
}
func (m *UpdateProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRes proto.InternalMessageInfo

func (m *UpdateProductRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeleteProductReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductReq) Reset()         { *m = DeleteProductReq{} }
func (m *DeleteProductReq) String() string { return proto.CompactTextString(m) }
func (*DeleteProductReq) ProtoMessage()    {}
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{7}
}

func (m *DeleteProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductReq.Unmarshal(m, b)
}
func (m *DeleteProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductReq.Marshal(b, m, deterministic)
}
func (m *DeleteProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductReq.Merge(m, src)
}
func (m *DeleteProductReq) XXX_Size() int {
	return xxx_messageInfo_DeleteProductReq.Size(m)
}
func (m *DeleteProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductReq proto.InternalMessageInfo

func (m *DeleteProductReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRes) Reset()         { *m = DeleteProductRes{} }
func (m *DeleteProductRes) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRes) ProtoMessage()    {}
func (*DeleteProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{8}
}

func (m *DeleteProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRes.Unmarshal(m, b)
}
func (m *DeleteProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRes.Marshal(b, m, deterministic)
}
func (m *DeleteProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRes.Merge(m, src)
}
func (m *DeleteProductRes) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRes.Size(m)
}
func (m *DeleteProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRes proto.InternalMessageInfo

func (m *DeleteProductRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetAllProductsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductsReq) Reset()         { *m = GetAllProductsReq{} }
func (m *GetAllProductsReq) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsReq) ProtoMessage()    {}
func (*GetAllProductsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{9}
}

func (m *GetAllProductsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsReq.Unmarshal(m, b)
}
func (m *GetAllProductsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsReq.Marshal(b, m, deterministic)
}
func (m *GetAllProductsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsReq.Merge(m, src)
}
func (m *GetAllProductsReq) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsReq.Size(m)
}
func (m *GetAllProductsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsReq proto.InternalMessageInfo

type GetAllProductsRes struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductsRes) Reset()         { *m = GetAllProductsRes{} }
func (m *GetAllProductsRes) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsRes) ProtoMessage()    {}
func (*GetAllProductsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{10}
}

func (m *GetAllProductsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsRes.Unmarshal(m, b)
}
func (m *GetAllProductsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsRes.Marshal(b, m, deterministic)
}
func (m *GetAllProductsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsRes.Merge(m, src)
}
func (m *GetAllProductsRes) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsRes.Size(m)
}
func (m *GetAllProductsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsRes proto.InternalMessageInfo

func (m *GetAllProductsRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*CreateProductReq)(nil), "product.CreateProductReq")
	proto.RegisterType((*CreateProductRes)(nil), "product.CreateProductRes")
	proto.RegisterType((*GetProductReq)(nil), "product.GetProductReq")
	proto.RegisterType((*GetProductRes)(nil), "product.GetProductRes")
	proto.RegisterType((*UpdateProductReq)(nil), "product.UpdateProductReq")
	proto.RegisterType((*UpdateProductRes)(nil), "product.UpdateProductRes")
	proto.RegisterType((*DeleteProductReq)(nil), "product.DeleteProductReq")
	proto.RegisterType((*DeleteProductRes)(nil), "product.DeleteProductRes")
	proto.RegisterType((*GetAllProductsReq)(nil), "product.GetAllProductsReq")
	proto.RegisterType((*GetAllProductsRes)(nil), "product.GetAllProductsRes")
}

func init() { proto.RegisterFile("proto/product.proto", fileDescriptor_cfd9ed8e6077aee0) }

var fileDescriptor_cfd9ed8e6077aee0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xd1, 0xda, 0x76, 0x4a, 0x4b, 0xdd, 0x8a, 0xac, 0x7b, 0x51, 0xf6, 0x24, 0x22, 0x55,
	0xea, 0x51, 0x51, 0xfc, 0xa2, 0xe0, 0x49, 0x22, 0x5e, 0xbc, 0xb5, 0xc9, 0x20, 0x81, 0x60, 0xd2,
	0xdd, 0x8d, 0xd0, 0x83, 0xbf, 0xd9, 0xbf, 0x20, 0xd9, 0x7c, 0x98, 0xdd, 0x98, 0x43, 0xf0, 0x96,
	0x37, 0xef, 0xcd, 0xec, 0xdb, 0x79, 0x4b, 0x60, 0x1a, 0x8b, 0x48, 0x45, 0x67, 0xb1, 0x88, 0xfc,
	0xc4, 0x53, 0x33, 0x8d, 0x48, 0x2f, 0x87, 0xfc, 0x0b, 0x7a, 0xcf, 0xd9, 0x27, 0x19, 0x83, 0x13,
	0xf8, 0xb4, 0x73, 0xd4, 0x39, 0x1e, 0xb8, 0x4e, 0xe0, 0x13, 0x06, 0x7d, 0x6f, 0xa9, 0xf0, 0x3d,
	0x12, 0x1b, 0xea, 0xe8, 0x6a, 0x89, 0xc9, 0x1e, 0x74, 0x55, 0xa0, 0x42, 0xa4, 0x5b, 0x9a, 0xc8,
	0x40, 0x5a, 0x8d, 0x45, 0xe0, 0x21, 0xdd, 0xce, 0xaa, 0x1a, 0xa4, 0x73, 0xd6, 0xc9, 0xf2, 0x43,
	0x05, 0x6a, 0x43, 0xbb, 0xd9, 0x9c, 0x02, 0xf3, 0x6b, 0x98, 0xdc, 0x0b, 0x5c, 0x2a, 0xcc, 0x4d,
	0xb8, 0xb8, 0x26, 0x27, 0x50, 0xb8, 0xd3, 0x66, 0x86, 0xf3, 0xc9, 0xac, 0x30, 0x5f, 0xa8, 0x4a,
	0xfb, 0xf5, 0x7e, 0xd9, 0xaa, 0xff, 0x10, 0x46, 0x0b, 0x54, 0x95, 0xc3, 0xad, 0x25, 0xf0, 0x4b,
	0x53, 0x20, 0xdb, 0xba, 0x7b, 0x8d, 0xfd, 0x7f, 0xdd, 0xce, 0xea, 0x6f, 0x77, 0x3e, 0x87, 0xc9,
	0x03, 0x86, 0x68, 0x9c, 0x6f, 0x5f, 0xf0, 0xb4, 0xa6, 0x91, 0x84, 0x42, 0x4f, 0x26, 0x9e, 0x87,
	0x52, 0x6a, 0x61, 0xdf, 0x2d, 0x20, 0x9f, 0xc2, 0xee, 0x02, 0xd5, 0x6d, 0x18, 0xe6, 0x6a, 0xe9,
	0xe2, 0x9a, 0xdf, 0xd4, 0x8b, 0xad, 0x7c, 0xce, 0xbf, 0x1d, 0x18, 0xe7, 0xc5, 0x17, 0x14, 0x9f,
	0xe9, 0xa3, 0x79, 0x84, 0x91, 0x11, 0x2c, 0x39, 0x28, 0xdb, 0xed, 0x07, 0xc3, 0x1a, 0x29, 0x49,
	0xae, 0x00, 0x7e, 0xe3, 0x23, 0xfb, 0xa5, 0xd0, 0x08, 0x9d, 0xfd, 0x5d, 0x97, 0xa9, 0x09, 0x63,
	0xff, 0x15, 0x13, 0x76, 0xae, 0xac, 0x91, 0xd2, 0x63, 0x8c, 0x15, 0x57, 0xc6, 0xd8, 0xf1, 0xb0,
	0x46, 0x4a, 0x92, 0x27, 0x18, 0x9b, 0x6b, 0x26, 0xac, 0xea, 0xdb, 0x0c, 0x85, 0x35, 0x73, 0xf2,
	0xbc, 0x73, 0x37, 0x7c, 0x1b, 0xe4, 0x74, 0xbc, 0x5a, 0xed, 0xe8, 0x7f, 0xc2, 0xc5, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x74, 0xc5, 0x11, 0xd3, 0x2a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductRes, error)
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductRes, error)
	UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductRes, error)
	DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductRes, error)
	GetAllProducts(ctx context.Context, in *GetAllProductsReq, opts ...grpc.CallOption) (ProductService_GetAllProductsClient, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductRes, error) {
	out := new(CreateProductRes)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductRes, error) {
	out := new(GetProductRes)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductRes, error) {
	out := new(UpdateProductRes)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductRes, error) {
	out := new(DeleteProductRes)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAllProducts(ctx context.Context, in *GetAllProductsReq, opts ...grpc.CallOption) (ProductService_GetAllProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProductService_serviceDesc.Streams[0], "/product.ProductService/GetAllProducts", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceGetAllProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_GetAllProductsClient interface {
	Recv() (*GetAllProductsRes, error)
	grpc.ClientStream
}

type productServiceGetAllProductsClient struct {
	grpc.ClientStream
}

func (x *productServiceGetAllProductsClient) Recv() (*GetAllProductsRes, error) {
	m := new(GetAllProductsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	CreateProduct(context.Context, *CreateProductReq) (*CreateProductRes, error)
	GetProduct(context.Context, *GetProductReq) (*GetProductRes, error)
	UpdateProduct(context.Context, *UpdateProductReq) (*UpdateProductRes, error)
	DeleteProduct(context.Context, *DeleteProductReq) (*DeleteProductRes, error)
	GetAllProducts(*GetAllProductsReq, ProductService_GetAllProductsServer) error
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) CreateProduct(ctx context.Context, req *CreateProductReq) (*CreateProductRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProduct(ctx context.Context, req *GetProductReq) (*GetProductRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductReq) (*UpdateProductRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductReq) (*DeleteProductRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetAllProducts(req *GetAllProductsReq, srv ProductService_GetAllProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllProducts not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAllProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllProductsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).GetAllProducts(m, &productServiceGetAllProductsServer{stream})
}

type ProductService_GetAllProductsServer interface {
	Send(*GetAllProductsRes) error
	grpc.ServerStream
}

type productServiceGetAllProductsServer struct {
	grpc.ServerStream
}

func (x *productServiceGetAllProductsServer) Send(m *GetAllProductsRes) error {
	return x.ServerStream.SendMsg(m)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllProducts",
			Handler:       _ProductService_GetAllProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/product.proto",
}
